[package]
name = "venvcache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
fd-lock = "4.0.2"
sha256 = { version = "1.5.0", default-features = false }
structopt = "0.3.26"
